2025-04-15 13:15:06 [main] ERROR serviceImpl.UserServiceImpl - Something went wrong during fetching user
java.util.NoSuchElementException: null
	at java.base/java.util.ArrayList.getFirst(ArrayList.java:440)
	at java.base/java.util.Optional.map(Optional.java:260)
	at repository.daoimpl.UserDaoImpl.fetchUserByEmail(UserDaoImpl.java:76)
	at serviceImpl.UserServiceImpl.checkUserPrentOrNot(UserServiceImpl.java:112)
	at serviceImpl.AuthenticationServiceImpl.userLogin(AuthenticationServiceImpl.java:44)
	at userInterface.Home.validateUser(Home.java:133)
	at userInterface.Home.homeScreen(Home.java:67)
	at Main.main(Main.java:11)
2025-04-15 14:47:46 [main] ERROR serviceImpl.UserServiceImpl - Something went wrong during fetching user
java.util.NoSuchElementException: null
	at java.base/java.util.ArrayList.getFirst(ArrayList.java:440)
	at java.base/java.util.Optional.map(Optional.java:260)
	at repository.daoimpl.UserDaoImpl.fetchUserByEmail(UserDaoImpl.java:76)
	at serviceImpl.UserServiceImpl.checkUserPrentOrNot(UserServiceImpl.java:112)
	at serviceImpl.AuthenticationServiceImpl.userLogin(AuthenticationServiceImpl.java:44)
	at userInterface.Home.validateUser(Home.java:133)
	at userInterface.Home.homeScreen(Home.java:67)
	at Main.main(Main.java:11)
2025-04-15 14:51:47 [main] ERROR serviceImpl.UserServiceImpl - something went wrong at user add 
java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_email_key"
  Detail: Key (email)=(chetan@gmail.com) already exists.
	at repository.daoimpl.UserDaoImpl.add(UserDaoImpl.java:35)
	at serviceImpl.UserServiceImpl.addUser(UserServiceImpl.java:27)
	at serviceImpl.AuthenticationServiceImpl.userRegistration(AuthenticationServiceImpl.java:27)
	at userInterface.Home.validateUser(Home.java:125)
	at userInterface.Home.homeScreen(Home.java:68)
	at Main.main(Main.java:11)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_email_key"
  Detail: Key (email)=(chetan@gmail.com) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:155)
	at repository.daoimpl.UserDaoImpl.add(UserDaoImpl.java:33)
	... 5 common frames omitted
2025-04-15 14:52:33 [main] ERROR serviceImpl.UserServiceImpl - Something went wrong  while inserting user..
java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_email_key"
  Detail: Key (email)=(chetan@gmail.com) already exists.
	at repository.daoimpl.UserDaoImpl.updateUser(UserDaoImpl.java:54)
	at serviceImpl.UserServiceImpl.updateUser(UserServiceImpl.java:45)
	at userInterface.common.UpdateUser.emailUpdate(UpdateUser.java:73)
	at userInterface.common.UpdateUser.updateData(UpdateUser.java:48)
	at userInterface.common.UpdateUser.updateUser(UpdateUser.java:37)
	at userInterface.dashboard.DashboardUser.profileView(DashboardUser.java:77)
	at userInterface.dashboard.DashboardUser.userScreen(DashboardUser.java:54)
	at userInterface.Home.isLoginUser(Home.java:83)
	at userInterface.Home.homeScreen(Home.java:67)
	at Main.main(Main.java:11)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_email_key"
  Detail: Key (email)=(chetan@gmail.com) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:155)
	at repository.daoimpl.UserDaoImpl.updateUser(UserDaoImpl.java:52)
	... 9 common frames omitted
2025-04-15 14:58:16 [main] ERROR serviceImpl.UserServiceImpl - Something went wrong  while inserting user..
java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_email_key"
  Detail: Key (email)=(chetan@gmail.com) already exists.
	at repository.daoimpl.UserDaoImpl.updateUser(UserDaoImpl.java:54)
	at serviceImpl.UserServiceImpl.updateUser(UserServiceImpl.java:45)
	at userInterface.common.UpdateUser.emailUpdate(UpdateUser.java:76)
	at userInterface.common.UpdateUser.updateData(UpdateUser.java:49)
	at userInterface.common.UpdateUser.updateUser(Unknown Source)
	at userInterface.dashboard.DashboardUser.profileView(DashboardUser.java:77)
	at userInterface.dashboard.DashboardUser.userScreen(DashboardUser.java:54)
	at userInterface.Home.isLoginUser(Home.java:83)
	at userInterface.Home.homeScreen(Home.java:67)
	at Main.main(Main.java:11)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_email_key"
  Detail: Key (email)=(chetan@gmail.com) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:155)
	at repository.daoimpl.UserDaoImpl.updateUser(UserDaoImpl.java:52)
	... 9 common frames omitted
2025-04-15 14:58:58 [main] ERROR serviceImpl.UserServiceImpl - Something went wrong  while inserting user..
java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_email_key"
  Detail: Key (email)=(chetan@gmail.com) already exists.
	at repository.daoimpl.UserDaoImpl.updateUser(UserDaoImpl.java:54)
	at serviceImpl.UserServiceImpl.updateUser(UserServiceImpl.java:45)
	at userInterface.common.UpdateUser.emailUpdate(UpdateUser.java:76)
	at userInterface.common.UpdateUser.updateData(UpdateUser.java:49)
	at userInterface.common.UpdateUser.updateUser(UpdateUser.java:38)
	at userInterface.dashboard.DashboardUser.profileView(DashboardUser.java:77)
	at userInterface.dashboard.DashboardUser.userScreen(DashboardUser.java:54)
	at userInterface.Home.isLoginUser(Home.java:83)
	at userInterface.Home.homeScreen(Home.java:67)
	at Main.main(Main.java:11)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_email_key"
  Detail: Key (email)=(chetan@gmail.com) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:155)
	at repository.daoimpl.UserDaoImpl.updateUser(UserDaoImpl.java:52)
	... 9 common frames omitted
2025-04-15 19:47:56 [main] ERROR serviceImpl.UserServiceImpl - Something went wrong during fetching user
java.util.NoSuchElementException: null
	at java.base/java.util.ArrayList.getFirst(ArrayList.java:440)
	at java.base/java.util.Optional.map(Optional.java:260)
	at repository.daoimpl.UserDaoImpl.fetchUserByEmail(UserDaoImpl.java:76)
	at serviceImpl.UserServiceImpl.checkUserPrentOrNot(UserServiceImpl.java:112)
	at serviceImpl.AuthenticationServiceImpl.userLogin(AuthenticationServiceImpl.java:44)
	at userInterface.Home.validateUser(Home.java:98)
	at userInterface.Home.homeScreen(Home.java:32)
	at Main.main(Main.java:11)
2025-04-15 19:55:56 [main] ERROR serviceImpl.UserServiceImpl - Something went wrong during fetching user
java.util.NoSuchElementException: null
	at java.base/java.util.ArrayList.getFirst(ArrayList.java:440)
	at java.base/java.util.Optional.map(Optional.java:260)
	at repository.daoimpl.UserDaoImpl.fetchUserByEmail(UserDaoImpl.java:76)
	at serviceImpl.UserServiceImpl.checkUserPrentOrNot(UserServiceImpl.java:112)
	at serviceImpl.AuthenticationServiceImpl.userLogin(AuthenticationServiceImpl.java:44)
	at userInterface.Home.validateUser(Home.java:98)
	at userInterface.Home.homeScreen(Home.java:32)
	at Main.main(Main.java:11)
